

#define SECTOR_KOEF 0x10

#define EE_AVT_ON		SECTOR_KOEF
#define EE_IMAX			SECTOR_KOEF+2
#define EE_IAVAR		SECTOR_KOEF+4
#define EE_TZPK 		SECTOR_KOEF+6
#define EE_PRL_PROG		SECTOR_KOEF+8
#define EE_AVT_ON_TUMBLER	SECTOR_KOEF+10
#define EE_ADR			SECTOR_KOEF+12
#define EE_K_U			SECTOR_KOEF+14
#define EE_K0_I		SECTOR_KOEF+16
#define EE_K1_I		SECTOR_KOEF+18
#define EE_K_T			SECTOR_KOEF+20
#define EE_BAUDRATE		SECTOR_KOEF+22
#define EE_I_SET		SECTOR_KOEF+24
#define EE_WRK_TIME		SECTOR_KOEF+26
#define EE_TEN_SET		SECTOR_KOEF+28
#define EE_AV_TEN_STAT0	SECTOR_KOEF+30
#define EE_AV_TEN_STAT1	SECTOR_KOEF+32
#define EE_AV_TEN_STAT2	SECTOR_KOEF+34
#define EE_AV_TEN_STAT3	SECTOR_KOEF+36
#define EE_AV_TEN_STAT4	SECTOR_KOEF+38
#define EE_TEN_WRK_CNT0	SECTOR_KOEF+40
#define EE_TEN_WRK_CNT1	SECTOR_KOEF+42
#define EE_TEN_WRK_CNT2	SECTOR_KOEF+44
#define EE_TEN_WRK_CNT3	SECTOR_KOEF+46
#define EE_TEN_WRK_CNT4	SECTOR_KOEF+48
#define EE_TEN_WRK_CNT_ROBIN0	SECTOR_KOEF+50
#define EE_TEN_WRK_CNT_ROBIN1	SECTOR_KOEF+52
#define EE_TEN_WRK_CNT_ROBIN2	SECTOR_KOEF+54
#define EE_TEN_WRK_CNT_ROBIN3	SECTOR_KOEF+56
#define EE_TEN_WRK_CNT_ROBIN4	SECTOR_KOEF+58
#define EE_I_SET				SECTOR_KOEF+60
#define EE_I_SET0				SECTOR_KOEF+60
#define EE_I_SET1				SECTOR_KOEF+62
#define EE_I_SET2				SECTOR_KOEF+64
#define EE_I_SET3				SECTOR_KOEF+66
#define EE_I_SET4				SECTOR_KOEF+68
#define EE_I_SET5				SECTOR_KOEF+70
#define EE_I_SET6				SECTOR_KOEF+72
#define EE_I_SET7				SECTOR_KOEF+74
#define EE_KON_SET				SECTOR_KOEF+76
#define EE_KON_SET0				SECTOR_KOEF+78
#define EE_KON_SET1				SECTOR_KOEF+80
#define EE_KON_SET2				SECTOR_KOEF+82
#define EE_KON_SET3				SECTOR_KOEF+84
#define EE_KON_SET4				SECTOR_KOEF+86
#define EE_KON_SET5				SECTOR_KOEF+88
#define EE_KON_SET6				SECTOR_KOEF+90
#define EE_KON_SET7				SECTOR_KOEF+92
#define EE_TP_SET				SECTOR_KOEF+94
#define EE_TP_SET0				SECTOR_KOEF+96
#define EE_TP_SET1				SECTOR_KOEF+98
#define EE_TP_SET2				SECTOR_KOEF+100
#define EE_TP_SET3				SECTOR_KOEF+102
#define EE_TP_SET4				SECTOR_KOEF+104
#define EE_TP_SET5				SECTOR_KOEF+106
#define EE_TP_SET6				SECTOR_KOEF+108
#define EE_TP_SET7				SECTOR_KOEF+110
#define EE_TV_SET				SECTOR_KOEF+114
#define EE_TV_SET0				SECTOR_KOEF+114
#define EE_TV_SET1				SECTOR_KOEF+116
#define EE_TV_SET2				SECTOR_KOEF+118
#define EE_TV_SET3				SECTOR_KOEF+120
#define EE_TV_SET4				SECTOR_KOEF+122
#define EE_TV_SET5				SECTOR_KOEF+124
#define EE_TV_SET6				SECTOR_KOEF+126
#define EE_TV_SET7				SECTOR_KOEF+128
#define EE_KV_SET				SECTOR_KOEF+132
#define EE_KV_SET0				SECTOR_KOEF+132
#define EE_KV_SET1				SECTOR_KOEF+134
#define EE_KV_SET2				SECTOR_KOEF+136
#define EE_KV_SET3				SECTOR_KOEF+138
#define EE_KV_SET4				SECTOR_KOEF+140
#define EE_KV_SET5				SECTOR_KOEF+142
#define EE_KV_SET6				SECTOR_KOEF+144
#define EE_KV_SET7				SECTOR_KOEF+146
#define EE_AVT_REP_SET0			SECTOR_KOEF+146
#define EE_AVT_REP_SET1			SECTOR_KOEF+148
#define EE_AVT_REP_SET2			SECTOR_KOEF+150
#define EE_AVT_REP_SET3			SECTOR_KOEF+152
#define EE_AVT_REP_SET4			SECTOR_KOEF+154
#define EE_AVT_REP_SET5			SECTOR_KOEF+156
#define EE_AVT_REP_SET6			SECTOR_KOEF+158
#define EE_AVT_REP_SET7			SECTOR_KOEF+160
#define EE_AVT_PER_SET0			SECTOR_KOEF+162
#define EE_AVT_PER_SET1			SECTOR_KOEF+164
#define EE_AVT_PER_SET2			SECTOR_KOEF+166
#define EE_AVT_PER_SET3			SECTOR_KOEF+168
#define EE_AVT_PER_SET4			SECTOR_KOEF+170
#define EE_AVT_PER_SET5			SECTOR_KOEF+172
#define EE_AVT_PER_SET6			SECTOR_KOEF+174
#define EE_AVT_PER_SET7			SECTOR_KOEF+176
#define EE_ALG_MODE				SECTOR_KOEF+178
#define EE_AKT_CH_ALG_1		    	SECTOR_KOEF+180
#define EE_REP_NUM_ALG_2			SECTOR_KOEF+182
#define EE_MODBUS_TYPE			SECTOR_KOEF+184

extern const signed short ADR_EE_I_SET[];
extern const signed short ADR_EE_KON_SET[];
extern const signed short ADR_EE_TP_SET[];
extern const signed short ADR_EE_TV_SET[];
extern const signed short ADR_EE_KV_SET[];
extern const signed short ADR_EE_AVT_REP_SET[];
extern const signed short ADR_EE_AVT_PER_SET[];